Vagrant.require_version ">= 1.8.4"

Vagrant.configure(2) do |config|
  $rpm_script = <<SCRIPT
# copy local config
sudo mkdir -p /etc/opt/mondoo
sudo mv /tmp/mondoo.yml /etc/opt/mondoo/.mondoo.yml

# install mondoo
echo Installing the mondoo-agent via RPM ...
curl --silent --location https://releases.mondoo.io/rpm/mondoo.repo | tee /etc/yum.repos.d/mondoo.repo
yum install -y mondoo
SCRIPT

  config.vm.define "centos" do |centos|
    centos.vm.box = "bento/centos-7.5"
    centos.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
    centos.vm.synced_folder ".", "/vagrant", disabled: true
    # optional step, makes it easy to push the config into the vagrant machine
    centos.vm.provision "file", source: "mondoo.yml", destination: "/tmp/mondoo.yml"
    centos.vm.provision "shell", inline: $rpm_script
  end

  $dpkg_script = <<SCRIPT
# copy local config
sudo mkdir -p /etc/opt/mondoo
sudo mv /tmp/mondoo.yml /etc/opt/mondoo/.mondoo.yml

# install mondoo
echo Installing the mondoo via apt ...
sudo apt-get install -y apt-transport-https ca-certificates
curl -sS https://releases.mondoo.io/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://releases.mondoo.io/debian/ stable main" | sudo tee /etc/apt/sources.list.d/mondoo.list
sudo apt-get update && sudo apt-get install mondoo
SCRIPT

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-18.04"
    ubuntu.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
    ubuntu.vm.synced_folder ".", "/vagrant", disabled: true
     # optional step, makes it easy to push the config into the vagrant machine
    ubuntu.vm.provision "file", source: "mondoo.yml", destination: "/tmp/mondoo.yml"
    ubuntu.vm.provision "shell", inline: $dpkg_script
  end


  config.vm.define "debian" do |debian|
    debian.vm.box = "bento/debian-9"
    debian.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
    debian.vm.synced_folder ".", "/vagrant", disabled: true
     # optional step, makes it easy to push the config into the vagrant machine
    debian.vm.provision "file", source: "mondoo.yml", destination: "/tmp/mondoo.yml"
    debian.vm.provision "shell", inline: $dpkg_script
  end
end

