# Mondoo Multi-Architecture Container Dockerfile
# 
# To build with BuildX:   docker buildx build --build-arg VERSION=5.21.0 --platform 
#             linux/amd64,linux/arm64 -t mondoolabs/mondoo:5.21.0 . --push

FROM redhat/ubi8-minimal AS root
ARG VERSION

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

ARG BASEURL="https://releases.mondoo.com/mondoo/${VERSION}"
ARG PACKAGE="mondoo_${VERSION}_${TARGETOS}_${TARGETARCH}${TARGETVARIANT}.tar.gz"

RUN microdnf upgrade -y &&\
    microdnf install wget tar rpm gzip -y &&\
    wget --quiet --output-document=SHA256SUMS ${BASEURL}/checksums.linux.txt &&\
    wget --quiet --output-document=${PACKAGE} ${BASEURL}/${PACKAGE} &&\
    cat SHA256SUMS | grep "${PACKAGE}" | sha256sum -c - &&\
    tar -xzC /usr/local/bin -f ${PACKAGE} &&\
    /usr/local/bin/mondoo version &&\
    rm -f ${PACKAGE} SHA256SUMS &&\
    microdnf remove wget tar gzip -y &&\
    rm -rf /var/cache/dnf/*

ENTRYPOINT [ "mondoo" ]
CMD ["help"]

# Rootless version of the container
FROM root AS rootless
USER 100:101
