name 'mondoo'
maintainer 'Mondoo, Inc'
maintainer_email 'hello@mondoo.io'
license 'Apache 2.0'
description 'Installs/Configures mondoo agent'
long_description 'Installs/Configures mondoo agent'
version '0.2.0'
chef_version '>= 14'

supports 'amazon'
supports 'ubuntu', '>= 16.04'
supports 'debian', '>= 9.0'
supports 'centos', '>= 6.0'
supports 'redhat', '>= 6.0'