name: tools - Federate to Azure OpenID Connect

on:
  workflow_dispatch:
  push:
    branches:
        - gary/azure-trusted-signer-ps

permissions:
  id-token: write
  contents: read

jobs:
  sign:
    runs-on: windows-latest
    environment: prod
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            install.ps1
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TSIGN_AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.TSIGN_AZURE_TENANT_ID}}
          subscription-id: ${{ vars.TSIGN_AZURE_SUBSCRIPTION_ID }}

      - name: Trusted Signing
        uses: azure/trusted-signing-action@v0
        with:
          endpoint: ${{ vars.TSIGN_AZURE_ENDPOINT }}
          trusted-signing-account-name: ${{ vars.TSIGN_ACCOUNT_NAME }}
          certificate-profile-name: ${{ vars.TSIGN_TEST_CERT_PROFILE_NAME }}
          files: |
            ${{ github.workspace }}\install.ps1
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA384
          exclude-environment-credential: true
          exclude-workload-identity-credential: true
          exclude-managed-identity-credential: true
          exclude-shared-token-cache-credential: true
          exclude-visual-studio-credential: true
          exclude-visual-studio-code-credential: true
          exclude-azure-cli-credential: false
          exclude-azure-powershell-credential: true
          exclude-azure-developer-cli-credential: true
          exclude-interactive-browser-credential: true
