name: "Check Mondoo's GPG key is not expired"
on:
  workflow_dispatch:
  # Run every day at 00:00
  schedule:
    - cron:  '0 0 * * *'

jobs:
  check_gpg:
    name: Check Mondoo's GPG key has not expired
    env:
      # C07R9GSGKEU == #mondoo-ops
      SLACK_BOT_CHANNEL_ID: "C07R9GSGKEU"

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - id: slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "${{ env.SLACK_BOT_CHANNEL_ID }}"
            text: "GitHub Actions Run"
            attachments:
              - color: "#FFFF00"
                blocks:
                  - type: "section"
                    fields:
                      - type: "mrkdwn"
                        text: "<${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}|${{ github.workflow }}>"
                      - type: "mrkdwn"
                        text: "*Status:*\n`In Progress`"
          
      - name: Install Mondoo cnspec
        shell: bash
        run: |
          echo Installing Mondoo cnspec...
          bash -xc "$(curl -sSL https://install.mondoo.com/sh/cnspec)"
      
      - name: Check expiration of public-package-signing.gpg
        shell: bash
        run: |
          cnspec providers install network
          cnspec scan local --detect-cicd --score-threshold 100 --policy-bundle test/cnspec/check-gpg.mql.yaml -o full

      - name: Install OpenPGP & cURL
        run: sudo apt install gpg -y

      - name: Check Public GPG Signing Key Harmony
        shell: bash
        run: |
          bash test/scripts/cert-harmony.sh

      - uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        if: always()
        with:
          method: chat.update
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "${{ env.SLACK_BOT_CHANNEL_ID }}"
            ts: "${{ steps.slack.outputs.ts }}"
            text: "GitHub Actions Run"
            attachments:
              - color: "${{ job.status == 'success' && '#00FF00' || job.status == 'failure' && '#FF0000' || '#FFA500' }}"
                blocks:
                  - type: "section"
                    fields:
                      - type: "mrkdwn"
                        text: "<${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}|${{ github.workflow }}>"
                      - type: "mrkdwn"
                        text: "*Status:*\n`${{ job.status }}`"
