name: "PKG: Chocolatey NuGet Release"

on:
  workflow_call:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string
        default: "8.0.0"
      skip-publish:
        description: "Skip publish?"
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string
        default: "8.0.0"
      skip-publish:
        description: "Skip publish?"
        required: false
        default: false
        type: boolean

jobs:
  chocotize:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [cnquery, cnspec]
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate Package
        shell: bash
        run: |
          cd packages/chocolatey || exit
          echo "------- GENERATING ${{ matrix.package }} ----------------------"
          VERSION=${{ inputs.version }} bash ${{ matrix.package }}-generate.sh
          echo ""
          echo "Install script:"
          cat ${{ matrix.package }}/tools/chocolateyInstall.ps1
          echo "--------"

      - name: Update Chocolatey Package
        if: ${{ ! inputs.skip-publish }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/packages/chocolatey:/packages \
            -e CHOCO_API_KEY=${{ secrets.CHOCOLATEY_API_KEY }} \
            -e VERSION=${{ inputs.version }} \
            chocolatey/choco:latest \
            bash -c "
              cd /packages/${{ matrix.package }} &&
              choco apikey --key \${CHOCO_API_KEY} --source https://push.chocolatey.org/ &&
              choco pack &&
              choco push --source=https://push.chocolatey.org/
            "
          echo 'Go check for the moderation status:'
          echo 'Mondoo Moderation Queue: https://community.chocolatey.org/packages?q=tag%3Amondoo&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=relevance'
