name: "PKG: Chocolatey NuGet Release"

on:
  workflow_call:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string
        default: "8.0.0"
      skip-publish:
        description: "Skip publish?"
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string
        default: "8.0.0"
      skip-publish:
        description: "Skip publish?"
        required: false
        default: false
        type: boolean

jobs:
  chocotize:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [mql, cnspec, cnquery]
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Generate and Validate Package
        run: make -C packages/chocolatey generate validate VERSION=${{ inputs.version }} PACKAGES=${{ matrix.package }}

      - name: Pack Package
        run: make -C packages/chocolatey pack VERSION=${{ inputs.version }} PACKAGES=${{ matrix.package }}

      - name: Publish Package
        if: ${{ ! inputs.skip-publish }}
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
        run: make -C packages/chocolatey publish VERSION=${{ inputs.version }} PACKAGES=${{ matrix.package }} CHOCO_API_KEY=$CHOCO_API_KEY
