name: Test PowerShell Module

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pwsh_module_installation:
    name: Run PowerShell install module
    runs-on: windows-2022
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install mondoo package
        shell: powershell
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Get-PSRepository
          Install-Module -Name Mondoo.Installer -Force
          Install-Mondoo
          & 'C:\Program Files\Mondoo\cnspec.exe' version
