name: "Test Release: Docker Containers"

on:
  workflow_call:
    inputs:
      version:
        description: "Version to test"
        required: true
        default: "9.0.0"
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "Version to test"
        required: true
        default: "9.0.0"

permissions:
  contents: read

jobs:
  mql-containers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suffix: ["", "-ubi-rootless", "-rootless"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Version
        id: version
        env:
          INPUT_VERSION: ${{ inputs.version }}
        run: |
          VERSION=$(echo "${INPUT_VERSION}" | sed 's/^v//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Testing mondoo/mql:${{ steps.version.outputs.version }}${{ matrix.suffix }}....
        run: |
          version=$(docker run --rm -v $(pwd):/work -w /work mondoo/mql:${{ steps.version.outputs.version }}${{ matrix.suffix }} version)
          echo $version
          echo $version | grep -q ${{ steps.version.outputs.version }}
  cnspec-containers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suffix: ["", "-ubi-rootless", "-rootless"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Version
        id: version
        env:
          INPUT_VERSION: ${{ inputs.version }}
        run: |
          VERSION=$(echo "${INPUT_VERSION}" | sed 's/^v//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Testing mondoo/cnspec:${{ steps.version.outputs.version }}${{ matrix.suffix }}....
        run: |
          version=$(docker run --rm -v $(pwd):/work -w /work mondoo/cnspec:${{ steps.version.outputs.version }}${{ matrix.suffix }} version)
          echo $version
          echo $version | grep -q ${{ steps.version.outputs.version }}

  mondoo-containers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suffix: ["", "-ubi-rootless", "-rootless"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Version
        id: version
        env:
          INPUT_VERSION: ${{ inputs.version }}
        run: |
          VERSION=$(echo "${INPUT_VERSION}" | sed 's/^v//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Testing mondoo/client:${{ steps.version.outputs.version }}${{ matrix.suffix }}....
        run: |
          version=$(docker run --rm -v $(pwd):/work -w /work mondoo/client:${{ steps.version.outputs.version }}${{ matrix.suffix }} version)
          echo $version
          echo $version | grep -q ${{ steps.version.outputs.version }}
