name: "Test Release: Arch Linux"

on:
  workflow_call:
    inputs:
      version:
        description: "Version to test"
        required: true
        default: "9.0.0"
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "Version to test"
        required: true
        default: "9.0.0"

jobs:
  arch-mql-makepkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Version
        id: version
        run: |
          V=${{ inputs.version }}
          VERSION=$(echo $V | sed 's/^v//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'
      - name: Install pytest
        run: pip install pytest
      - name: Install mql with MakePKG on Arch Linux
        run: |
          pytest test/auto_update/test_aur.py::test_aur_mql_makepkg -v \
            --install-version ${{ steps.version.outputs.version }} \
            --distro arch

  arch-cnspec-yay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Version
        id: version
        run: |
          V=${{ inputs.version }}
          VERSION=$(echo $V | sed 's/^v//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'
      - name: Install pytest
        run: pip install pytest
      - name: Install cnspec with Yay on Arch Linux
        run: |
          pytest test/auto_update/test_aur.py::test_aur_cnspec_yay -v \
            --install-version ${{ steps.version.outputs.version }} \
            --distro arch

  arch-upgrade-cnquery-to-mql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Version
        id: version
        run: |
          V=${{ inputs.version }}
          VERSION=$(echo $V | sed 's/^v//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'
      - name: Install pytest
        run: pip install pytest
      - name: Upgrade cnquery -> mql on Arch Linux
        run: |
          pytest test/auto_update/test_upgrade.py::test_aur_upgrade -v \
            --install-version ${{ steps.version.outputs.version }} \
            --distro arch
